# Generated by Django 3.1.7 on 2022-02-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220224_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
